robotMovil/urls.py
from django.urls import path
from . import views

app_name = 'robotMovil'

urlpatterns = [
    path('index',views.index,name='index')
]

teleClient/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('robotMovil/',include('robotMovil.urls')),
]

robotMovil/models.py
from django.db import models

# Create your models here.

robotMovil/views.py
from django.shortcuts import render
import requests
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def index(request):
    mensaje_info = ''
    conectado = '0'
    url_consulta = ''
    if request.method == 'POST':
        ip_robot = request.POST.get('ipRobot')
        url_consulta = f'http://{ip_robot}:6060/robotMovil/verificarConexion'
        print(url_consulta)
        try:
            info = requests.get(url=url_consulta,timeout=1)
            conectado = '1'
            url_consulta = f'http://{ip_robot}:6060/robotMovil/'
        except:
            print('no se obtuvo conexion')
            conectado = '0'
            url_consulta = ''
            mensaje_info = 'No se pudo conectar'
    return render(request,'robotMovil/index.html',{
        'mensaje':mensaje_info,
        'conectado':conectado,
        'url_conexion':url_consulta,
    })

robotMovil/templates/robotMovil/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>RobotMovil</title>
    </head>
    <body>
        <form method="post" action="{% url 'robotMovil:index' %}">
        {% csrf_token %}
        <label>Ingrese la IP del robot a conectar : </label>
        <input type="text" name="ipRobot">
        <button type="submit">Ingresar</button>
        </form>
        <div>
            {% if mensaje %}
            <h1>{{ mensaje }}</h1>
            {% endif %}
        </div>
        <div>
            {% if conectado == '1' %}
            <a href="{{ url_conexion }}">Conectar</a>
            {% endif %}
        </div>
    </body>
</html>